credentials:
  usernames:
    user1:
      email: user1@example.com
      name: User One
      password: "hashed_password_1"
    user2:
      email: user2@example.com
      name: User Two
      password: "hashed_password_2"

cookie:
  name: 'todo_auth'
  key: 'random_secret_key'
  expiry_days: 30
